[settings]
color_theme = "catppuccin"

[tools]
"cargo:atuin" = "latest"
"cargo:bilal" = "latest"
"cargo:bob-nvim" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-update" = "latest"
"cargo:digs" = "latest"
"cargo:dotter" = "latest"
"cargo:dprint" = "latest"
"cargo:dua-cli" = "latest"
"cargo:emacs-lsp-booster" = "latest"
"cargo:git-cliff" = "latest"
"cargo:gitu" = "latest"
"cargo:goup-rs" = "latest"
"cargo:jaq" = "latest"
"cargo:kondo" = "latest"
"cargo:nu" = "latest"
"cargo:nu-lint" = "latest"
"cargo:toor" = "latest"
"cargo:ttyper" = "latest"
"go:gotest.tools/gotestsum" = "latest"
just = "latest"
node = "26"
"pipx:grip" = "latest"
"pipx:qmk" = "latest"
"pipx:yt-dlp" = "latest"
pnpm = "latest"
poetry = "latest"
shellcheck = "latest"
uv = "latest"
zizmor = "latest"
