[package]
name = "xtool"
version = "0.0.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
anyhow = "1"
xflags = "0.3.1"
xshell = "0.2.3"

# age
humantime = "2"
time = { version = "0.3", features = ["formatting", "local-offset", "parsing"] }
