#!/usr/bin/env -S just --justfile

set dotenv-load := true

alias d := dev
alias p := deploy

[doc('List available commands')]
_default:
    just --list --unsorted

[confirm('⚠️ This command will alter your system. Run recipe `setup`?')]
[doc('Setup the repository')]
setup:
    cargo binstall cargo-edit cargo-outdated dprint git-cliff bacon typos-cli

[doc('Quality check')]
qq: qa test

[doc('Quick quality check')]
qa: fmt-check lint

[doc('Fix before check')]
qc: fix qq

[doc('Enforce rules')]
fix: fmt lint

[doc('Publish')]
deploy: qa test

[doc('Develop')]
dev:
    bacon
    just qc

[doc('Format')]
fmt:
    cargo fmt --all

[doc('Check formatting')]
fmt-check:
    cargo fmt --all -- --check

[doc('Lint')]
lint:
    cargo clippy --all-targets --all-features --quiet
    typos

[doc('Test')]
test:
    cargo test --quiet

[doc('Upgrade dependencies')]
up:
    cargo upgrade --incompatible --recursive --verbose
    cargo update
    dprint config update

[doc('Dependency analysis')]
meta:
    cargo +nightly udeps
    cargo audit
    cargo outdated --root-deps-only
