[main]
font=0xProto Nerd Font:size=22
font=emoji:Noto Emoji
include=~/.config/foot/themes/modus_vivendi.ini
pad=0x0

[cursor]
style=beam
blink=yes

[key-bindings]
clipboard-copy=Alt+w
clipboard-paste=Control+y

# [tweak]
# selection-target=clipboard
