# https://starship.rs/config/

command_timeout = 1000

[container]
style = 'bold blue dimmed'
format = '[$symbol]($style) '

[custom.container_name]
command = "cname"
when = "cname"
symbol = '🫙'
style = 'bold blue dimmed'
format = "[$symbol $output]($style) "
