# https://starship.rs/config/

[container]
style = 'bold blue dimmed'
format = '[$symbol]($style) '

[custom.container_name]
command = "container-name"
when = "container-name"
symbol = '🫙'
style = 'bold blue dimmed'
format = "[$symbol $output]($style) "
