# vim:ft=kitty

## name: Tokyo Black
## author: folke
# The basic colors
foreground              #ffffff
background              #000000
selection_foreground    #ffffff
selection_background    #283457
# Cursor colors
cursor                  #86e1fc
cursor_text_color       #000000
# kitty window border colors
active_border_color     #82aaff
inactive_border_color   #1b1d2b
# Tab bar colors
active_tab_foreground   #c099ff
active_tab_background   #000000
inactive_tab_foreground #828bb8
inactive_tab_background #000000
# The basic 16 colors
# black
color0  #1b1d2b
color8  #9aa5ce
# red
color1  #ff757f
color9  #ff8d94
# green
color2  #c3e88d
color10 #c7fb6d
# yellow
color3  #ffc777
color11 #ffd8ab
# blue
color4  #82aaff
color12 #9ab8ff
# magenta
color5  #c099ff
color13 #caabff
# cyan
color6  #86e1fc
color14 #b2ebff
# white
color7  #828bb8
color15 #c8d3f5
