inherits = "tokyonight_moon"

[palette]
comment = "#9399b2" # Overlay2
border-highlight = "#cdd6f4" # Border color on popup menu.

bg = "#000000"
bg-selection = "#45475a" # Surface1. Surface0 hard to distinguish. Active selection.
bg-menu = "#000000" # ui.popup bg.
bg-focus = "#313244" #  Surface0. active selection on popup menu.

fg = "#ffffff"
fg-dark = "#cdd6f4" # Text, subtext is too subtle. Modeline
fg-gutter = "#a6adc8" # Subtext1 is too bright. Inactive line number.
fg-linenr = "#fca7ea" # Active line number.
