# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#86e1fc" }

# Hovered
hovered = { fg = "#c8d3f5", bg = "#2f334d", bold = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#54546d", bg = "#c8d3f5", bold = true, italic = true }
find_position = { fg = "#c8d3f5", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#c3e88d", bg = "#c3e88d" }
marker_copied = { fg = "#ff757f", bg = "#ff757f" }
marker_cut = { fg = "#86e1fc", bg = "#86e1fc" }

# Tab
tab_active = { fg = "#222436", bg = "#c8d3f5" }
tab_inactive = { fg = "#ffc777", bg = "#9399b2" }
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#ff966c" }

# Offset
folder_offset = [1, 0, 1, 0]
preview_offset = [1, 1, 1, 1]

# Highlighting
syntect_theme = ""

# : }}}

# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#222436", bg = "#222436" }

# Mode
mode_normal = { fg = "#222436", bg = "#c8d3f5", bold = true }
mode_select = { fg = "#222436", bg = "#c3e88d", bold = true }
mode_unset = { fg = "#222436", bg = "#c8d3f5", bold = true }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#86e1fc", bg = "#222436" }
progress_error = { fg = "#86e1fc", bg = "#222436" }

# Permissions
permissions_t = { fg = "#c3e88d" }
permissions_r = { fg = "#ff757f" }
permissions_w = { fg = "#86e1fc" }
permissions_x = { fg = "#ff966c" }
permissions_s = { fg = "#222436", bg = "#222436" }

# : }}}

# : Input {{{

[input]
border = { fg = "#86e1fc" }
title = {}
value = {}
selected = { reversed = true }

# : }}}

# : Select {{{

[select]
border = { fg = "#86e1fc" }
active = { fg = "#c8d3f5" }
inactive = {}

# : }}}

# : Tasks {{{

[tasks]
border = { fg = "#86e1fc" }
title = {}
hovered = { underline = true }

# : }}}

# : Which {{{

[which]
mask = { bg = "#222436" }
cand = { fg = "#c8d3f5" }
rest = { fg = "#222436" }
desc = { fg = "#cdd6f4" }
separator = "  "
separator_style = { fg = "#222436" }

# : }}}

# : Help {{{

[help]
on = { fg = "#86e1fc" }
exec = { fg = "#c8d3f5" }
desc = { fg = "#cdd6f4" }
hovered = { bg = "#2f334d", bold = true }
footer = { fg = "#c8d3f5", bg = "#222436" }

# : }}}

# : File-specific styles {{{

[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "#86e1fc" },

    # Videos
    { mime = "video/*", fg = "#86e1fc" },
    { mime = "audio/*", fg = "#86e1fc" },

    # Archives
    { mime = "application/zip", fg = "#ff757f" },
    { mime = "application/gzip", fg = "#ff757f" },
    { mime = "application/x-tar", fg = "#ff757f" },
    { mime = "application/x-bzip", fg = "#ff757f" },
    { mime = "application/x-7z-compressed", fg = "#ff757f" },
    { mime = "application/x-rar", fg = "#ff757f" },

    # Custom color for common programming languages
    { name = "*.rs", fg = "#ffa066" },
    { name = "*.toml", fg = "#7e9cd8" },
    { name = "*.py", fg = "#7e9cd8" },
    { name = "*.md", fg = "#7e9cd8" },
    { name = "*.sh", fg = "#c3e88d" },
    { name = "*.js", fg = "#86e1fc" },
    { name = "*.json", fg = "#86e1fc" },
    { name = "*.c", fg = "#86e1fc" },
    { name = "*.html", fg = "#ff757f" },

    # Fallback
    # file
    { name = "*", fg = "#7e9cd8" },
    # directory
    { name = "*/", fg = "#c8d3f5" },
]

[icons]
"Desktop/" = ""
"Documents/" = ""
"Downloads/" = ""
"Pictures/" = ""
"Music/" = ""
"Movies/" = ""
"Videos/" = ""
"Public/" = ""
"Library/" = ""
"Development/" = ""
".config/" = ""

# Git
".git/" = ""
".gitignore" = ""
".gitmodules" = ""
".gitattributes" = ""

# Dotfiles
".DS_Store" = ""
".bashrc" = ""
".bashprofile" = ""
".zshrc" = ""
".zshenv" = ""
".zprofile" = ""
".vimrc" = ""

# Text
"*.txt" = ""
"*.md" = ""

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz" = ""
"*.7z" = ""

# Audio
"*.mp3" = ""
"*.flac" = ""
"*.wav" = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""

# Images
"*.jpg" = ""
"*.jpeg" = ""
"*.png" = ""
"*.gif" = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp" = ""
"*.ico" = ""
"*.svg" = ""

# Programming
"*.c" = ""
"*.cpp" = ""
"*.h" = ""
"*.hpp" = ""
"*.rs" = ""
"*.go" = ""
"*.py" = ""
"*.js" = ""
"*.ts" = ""
"*.tsx" = ""
"*.jsx" = ""
"*.rb" = ""
"*.php" = ""
"*.java" = ""
"*.sh" = ""
"*.fish" = ""
"*.swift" = ""
"*.vim" = ""
"*.lua" = ""
"*.html" = ""
"*.css" = ""
"*.scss" = ""
"*.json" = ""
"*.toml" = ""
"*.yml" = ""
"*.yaml" = ""
"*.ini" = ""
"*.conf" = ""

# Default
"*" = ""
"*/" = ""

# : }}}
