[colors]
foreground = "#dcd7ba"
background = "#1f1f28"

cursor_bg = "#c8c093"
cursor_fg = "#c8c093"
cursor_border = "#c8c093"
compose_cursor = "#e6c384"

selection_fg = "#c8c093"
selection_bg = "#2d4f67"

scrollbar_thumb = "#54546D"
split = "#54546D"

# [1]
# [2] Starship VCS status
# [3] Atuin time elapsed
# [4] `ls` file with extension, Starship elapsed time
# [5] `ls` directory, Starship version
# [6] Starship VCS branch
# [7] Starship Project name
# [8] `taze` progress bar
ansi = ["#090618", "#ff5d62", "#98bb6c", "#e6c384", "#7e9cd8", "#68AD99", "#a3d4d5", "#c8c093"]
# [1] Atuin page title
brights = ["#c8c093", "#ff5d62", "#98bb6c", "#e6c384", "#7e9cd8", "#68AD99", "#a3d4d5", "#dcd7ba"]

[colors.tab_bar]
inactive_tab_edge = "#1e2030"
background = "#222436"

[colors.tab_bar.active_tab]
fg_color = "#1e2030"
bg_color = "#a3d4d5"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#2f334d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a3d4d5"
bg_color = "#2f334d"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#a3d4d5"
bg_color = "#222436"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#a3d4d5"
bg_color = "#222436"
