[colors]
foreground = "#c8d3f5"
background = "#222436"

cursor_bg = "#c8d3f5"
cursor_fg = "#222436"
cursor_border = "#c8d3f5"
compose_cursor = "#86e1fc"

selection_bg = "#2d3f76"
selection_fg = "#c8d3f5"

split = "#82aaff"

scrollbar_thumb = "#2F334D"

ansi = [
    # Atuin page title
    "#1b1d2b",
    # Starship VCS status
    "#ff757f",
    # Atuin time elapsed
    "#c3e88d",
    # `ls` file with extension, Starship elapsed time
    "#ffc777",
    # `ls` directory, Starship version
    "#82aaff",
    # Starship VCS branch
    "#c099ff",
    # Starship Project name
    "#86e1fc",
    # `taze` progress bar
    "#828bb8",
]
brights = ["#444a73", "#ff757f", "#c3e88d", "#ffc777", "#82aaff", "#c099ff", "#86e1fc", "#c8d3f5"]

[colors.tab_bar]
inactive_tab_edge = "#1e2030"
background = "#222436"

[colors.tab_bar.active_tab]
fg_color = "#1e2030"
bg_color = "#82aaff"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#2f334d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#82aaff"
bg_color = "#2f334d"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#82aaff"
bg_color = "#222436"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#82aaff"
bg_color = "#222436"

[metadata]
aliases = []
name = "tokyonight_moon"
