[colors]
ansi = [
    '#3e4b59',
    '#f07178',
    '#b8cc52',
    '#ffee99',
    '#ff7733',
    '#ffee99',
    '#36a3d9',
    '#95e6cb',
]
brights = [
    '#3e4b59',
    '#f07178',
    '#b8cc52',
    '#ffee99',
    '#ff7733',
    '#ffee99',
    '#36a3d9',
    '#95e6cb',
]
foreground = '#e6e1cf'
background = '#000000'
cursor_bg = '#e6e1cf'
scrollbar_thumb = '#5c6773'


[metadata]
aliases = []
name = 'Ayu'
