# https://github.com/rebelot/kanagawa.nvim/blob/master/extras/wezterm.lua

[colors]
ansi = ["#090618", "#c34043", "#76946a", "#c0a36e", "#7e9cd8", "#957fb8", "#6a9589", "#c8c093"]
brights = ["#090618", "#c34043", "#76946a", "#c0a36e", "#7e9cd8", "#957fb8", "#6a9589", "#c8c093"]
foreground = '#dcd7ba'
background = '#000000'
cursor_bg = '#c8c093'
scrollbar_thumb = '#16161d'
split = "#16161d"

[metadata]
aliases = []
name = 'Kanagawa'
