[colors]
ansi = [
    '#7f849c',
    '#ff5370',
    '#c3e88d',
    '#ffcb6b',
    '#82aaff',
    '#C792EA',
    '#89ddff',
    '#ffffff',
]
brights = [
    '#7f849c',
    '#f07178',
    '#c3e88d',
    '#ffcb6b',
    '#82AAFF',
    '#C792EA',
    '#89DDFF',
    '#ffffff',
]
cursor_bg = '#79A8FF'

# All the colors below are kept across theme.
# Mostly taken from https://catppuccin.com/palette mocha.
foreground = '#ffffff'
background = '#000000'
scrollbar_thumb = '#7f849c'

[metadata]
aliases = []
name = 'Material'
