[colors]
ansi = ["#000000", "#ff5f59", "#44bc44", "#d0bc00", "#2fafff", "#feacd0", "#00d3d0", "#ffffff"]
brights = ["#000000", "#ff5f59", "#44bc44", "#d0bc00", "#2fafff", "#feacd0", "#00d3d0", "#ffffff"]
cursor_bg = '#00d3d0'

# All the colors below are kept across theme.
# Mostly taken from https://catppuccin.com/palette mocha.
foreground = '#ffffff'
background = '#000000'
scrollbar_thumb = '#7f849c'

[metadata]
aliases = []
author = "miikanissi"
name = "Modus Vivendi"
