[colors]
foreground = "#ffffff"
background = "#000000"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#7030af"
selection_fg = "#ffffff"
split = "#79a8ff"
compose_cursor = "#fec43f"
scrollbar_thumb = "#646464"

ansi = ["#000000", "#ff5f59", "#44bc44", "#d0bc00", "#2fafff", "#feacd0", "#00d3d0", "#ffffff"]
brights = ["#000000", "#ff5f59", "#44bc44", "#d0bc00", "#2fafff", "#feacd0", "#00d3d0", "#ffffff"]

[metadata]
aliases = []
author = "miikanissi"
name = "Modus Vivendi"
