[colors]
ansi = ["#7f849c", "#ff7f86", "#6ae4b9", "#dfaf7a", "#00bcff", "#feacd0", "#4ae2f0", "#ffffff"]
brights = ["#7f849c", "#ff7f86", "#6ae4b9", "#dfaf7a", "#00bcff", "#feacd0", "#4ae2f0", "#ffffff"]
cursor_bg = '#ff66ff' # (magenta intense)

# All the colors below are kept across theme.
# Mostly taken from https://catppuccin.com/palette mocha.
foreground = '#ffffff'
background = '#000000'
scrollbar_thumb = '#45475a'

[metadata]
