[colors]
ansi = ["#7f849c", "#ff7f86", "#00c06f", "#dfaf7a", "#00bcff", "#feacd0", "#6ae4b9", "#ffffff"]
brights = ["#7f849c", "#ff7f86", "#00c06f", "#dfaf7a", "#00bcff", "#feacd0", "#6ae4b9", "#ffffff"]
cursor_bg = '#ff66ff' (magenta intense)

# All the colors below are kept across theme.
# Mostly taken from https://catppuccin.com/palette mocha.
foreground = '#ffffff'
background = '#000000'
scrollbar_thumb = '#7f849c'

[metadata]
aliases = []
author = "miikanissi"
name = "Modus Vivendi"
