[colors]
ansi = [
    '#282a36',
    '#c5727a',
    '#b1c89d',
    '#efd49f',
    '#d79784',
    '#be9db8',
    '#88c0d0',
    '#9fc6c5',
]
brights = [
    '#282a36',
    '#c5727a',
    '#b1c89d',
    '#efd49f',
    '#d79784',
    '#be9db8',
    '#88c0d0',
    '#9fc6c5',
]
foreground = '#eceff4'
background = '#000000'
cursor_bg = '#eceff4'
scrollbar_thumb = '#4C4A4D'


[metadata]
aliases = []
name = 'Nordic'
