# https://github.com/EdenEast/nightfox.nvim/blob/main/extra/carbonfox/wezterm.toml

[colors]
ansi = ["#7f849c", "#ee5396", "#25be6a", "#08bdba", "#78a9ff", "#be95ff", "#33b1ff", "#ffffff"]
brights = ["#7f849c", "#ee5396", "#25be6a", "#08bdba", "#78a9ff", "#be95ff", "#33b1ff", "#ffffff"]
cursor_bg = '#ee5396'

# All the colors below are kept across theme.
# Mostly taken from https://catppuccin.com/palette mocha.
foreground = '#ffffff'
background = '#000000'
scrollbar_thumb = '#7f849c'

[metadata]
aliases = []
name = 'Oxocarbon'
