[colors]
ansi = [
    '#7f849c', # comments: jj comment,
    '#ff5c57', # error
    '#5af78e', # executables (filee), jj bookmark, atuin duration
    '#ff9f43', # specific files, prompt duration, jj author
    '#57c7ff', # directories (file), atuin time
    '#ff6ac1', # prompt: git branch
    '#9aedfe', # prompt: dir/project name
    '#ffffff',
]
brights = [
    '#7f849c',
    '#ff5c57',
    '#5af78e',
    '#ff9f43',
    '#57c7ff',
    '#ff6ac1',
    '#9aedfe',
    '#ffffff',
]
cursor_bg = '#ff6ac1'

# All the colors below are kept across theme.
# Mostly taken from https://catppuccin.com/palette mocha.
foreground = '#ffffff'
background = '#000000'
scrollbar_thumb = '#7f849c'

[metadata]
aliases = []
name = 'Snazzy'
