[theme]
name = "bad-wolf"

[icons]
name = "awesome"

[icons.overrides]
net_wireless = ""
net_wired = ""

[[block]]
block = "custom"
cycle = ["bilal -c", "bilal -n"]
on_click = "<command>"
interval = 300

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp0s20f3"
format = "{speed_down}:{speed_up}"
interval = 5
use_bits = false

[[block]]
block = "battery"
interval = 10
critical = 10
format = "{percentage}% {time}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a %Y-%m-%d %I:%M %p"
