[theme]
name = "gruvbox-light"

[theme.overrides]
idle_bg = "#312E81"
info_bg = "#312E81"
good_bg = "#312E81"

idle_fg = "#E0E7FF"
info_fg = "#E0E7FF"

warning_bg = "#d33682"
critical_bg = "#d33682"

[icons]
name = "awesome5"

[icons.overrides]
net_wireless = ""
net_wired = ""
net_up = ""
net_down = ""
zman = ""
bilal = ""

[[block]]
block = "net"
device = "wlp0s20f3"
format = "{speed_down}{speed_up}"
interval = 5

[[block]]
block = "battery"
interval = 10
critical = 10
format = "{percentage}{time}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization:1}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents:1}"

[[block]]
# time block can't cycle echo.
# I need both 12 and 24 hour format.
block = "custom"
cycle = ["echo  (date +'%a %Y-%m-%d %I:%M %p')", "echo  (date +'%a %Y-%m-%d %H:%M')"]
interval = 60
