# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
    # Navigation
    { on = ["i"], exec = "arrow -1", desc = "Move cursor up" },
    { on = ["e"], exec = "arrow 1", desc = "Move cursor down" },

    { on = ["I"], exec = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = ["E"], exec = "arrow 5", desc = "Move cursor down 5 lines" },

    { on = ["-"], exec = ["leave", "escape --visual --select"], desc = "Go back to the parent directory" },
    { on = ["n"], exec = ["leave", "escape --visual --select"], desc = "Go back to the parent directory" },
    { on = ["o"], exec = ["enter", "escape --visual --select"], desc = "Enter the child directory" },

    { on = ["Enter"], exec = ["enter", "escape --visual --select"], desc = "Enter the child directory" },

    { on = ["<A-n>"], exec = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = ["<A-e>"], exec = "seek 5", desc = "Seek down 5 units in the preview" },

    # Operation
    { on = ["<Enter>"], exec = ["enter", "escape --visual --select"], desc = "Enter the child directory" },
    { on = ["<C-Enter>"], exec = "open --interactive", desc = "Open the selected files interactively" },
]

[tasks]
prepend_keymap = [
    { on = ["i"], exec = "arrow -1", desc = "Move cursor up" },
    { on = ["e"], exec = "arrow 1", desc = "Move cursor down" },
]

[select]
prepend_keymap = [
    { on = ["n"], exec = "arrow -1", desc = "Move cursor up" },
    { on = ["e"], exec = "arrow 1", desc = "Move cursor down" },

    { on = ["N"], exec = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = ["E"], exec = "arrow 5", desc = "Move cursor down 5 lines" },

    # To disable a command, see https://github.com/sxyazi/yazi/discussions/629
    { on = ["<S-Up>"], exec = "disabled", desc = "Move cursor up 5 lines" },
    { on = ["<S-Down>"], exec = "disabled", desc = "Move cursor down 5 lines" },
]

[input]
prepend_keymap = [
    # Character-wise movement
    { on = ["n"], exec = "move -1", desc = "Move back a character" },
    { on = ["o"], exec = "move 1", desc = "Move forward a character" },
]

[completion]
prepend_keymap = [
    { on = ["<A-i>"], exec = "arrow -1", desc = "Move cursor up" },
    { on = ["<A-e>"], exec = "arrow 1", desc = "Move cursor down" },
]

[help]
prepend_keymap = [
    # Navigation
    { on = ["e"], exec = "arrow -1", desc = "Move cursor up" },
    { on = ["n"], exec = "arrow 1", desc = "Move cursor down" },

    { on = ["E"], exec = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = ["N"], exec = "arrow 5", desc = "Move cursor down 5 lines" },
]
