# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#7AA89F" }

# Hovered
hovered = { fg = "#1F1F28", bg = "#f8b659" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#E82424", italic = true }
find_position = { fg = "#BD93F9", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#9EC967", bg = "#9EC967" }
marker_copied = { fg = "#E82424", bg = "#E82424" }
marker_cut = { fg = "#E46A78", bg = "#E46A78" }

# Tab
tab_active = { fg = "#1F1F28", bg = "#BD93F9" }
tab_inactive = { fg = "#DDD8BB", bg = "#44475A" }
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#f8b659" }

# Offset
folder_offset = [1, 0, 1, 0]
preview_offset = [1, 1, 1, 1]

# Highlighting
syntect_theme = ""

# : }}}

# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#44475A", bg = "#44475A" }
# Mode
mode_normal = { fg = "#1F1F28", bg = "#BD93F9", bold = true }
mode_select = { fg = "#1F1F28", bg = "#9EC967", bold = true }
mode_unset = { fg = "#1F1F28", bg = "#BD93F9", bold = true }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#8BE9FD", bg = "#1F1F28" }
progress_error = { fg = "#E46A78", bg = "#1F1F28" }

# Permissions
permissions_t = { fg = "#9EC967" }
permissions_r = { fg = "#E82424" }
permissions_w = { fg = "#E46A78" }
permissions_x = { fg = "#f8b659" }
permissions_s = { fg = "#44475A", bg = "#44475A" }

# : }}}

# : Input {{{

[input]
border = { fg = "#8BE9FD" }
title = {}
value = {}
selected = { reversed = true }

# : }}}

# : Select {{{

[select]
border = { fg = "#8BE9FD" }
active = { fg = "#BD93F9" }
inactive = {}

# : }}}

# : Tasks {{{

[tasks]
border = { fg = "#8BE9FD" }
title = {}
hovered = { underline = true }

# : }}}

# : Which {{{

[which]
mask = { bg = "#1F1F28" }
cand = { fg = "#f8b659" }
rest = { fg = "#44475A" }
desc = { fg = "#BD93F9" }
separator = "  "
separator_style = { fg = "#44475A" }

# : }}}

# : Help {{{

[help]
on = { fg = "#BD93F9" }
exec = { fg = "#f8b659" }
desc = { fg = "#44475A" }
hovered = { bg = "#44475A", bold = true }
footer = { fg = "#1F1F28", bg = "#BD93F9" }

# : }}}

# : File-specific styles {{{

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#8BE9FD" },

  # Videos
  { mime = "video/*", fg = "#FFB86C" },
  { mime = "audio/*", fg = "#FFB86C" },

  # Archives
  { mime = "application/zip", fg = "#E82424" },
  { mime = "application/gzip", fg = "#E82424" },
  { mime = "application/x-tar", fg = "#E82424" },
  { mime = "application/x-bzip", fg = "#001440" },
  { mime = "application/x-7z-compressed", fg = "#001440" },
  { mime = "application/x-rar", fg = "#44475A" },

  # Custom color for Rust files
  { name = "*.rs", fg = "#ea580c" },

  # Fallback
  { name = "*", fg = "white" },
  { name = "*/", fg = "#7BC2DF" },
]

[icons]
"Desktop/" = ""
"Documents/" = ""
"Downloads/" = ""
"Pictures/" = ""
"Music/" = ""
"Movies/" = ""
"Videos/" = ""
"Public/" = ""
"Library/" = ""
"Development/" = ""
".config/" = ""

# Git
".git/" = ""
".gitignore" = ""
".gitmodules" = ""
".gitattributes" = ""

# Dotfiles
".DS_Store" = ""
".bashrc" = ""
".bashprofile" = ""
".zshrc" = ""
".zshenv" = ""
".zprofile" = ""
".vimrc" = ""

# Text
"*.txt" = ""
"*.md" = ""

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz" = ""
"*.7z" = ""

# Audio
"*.mp3" = ""
"*.flac" = ""
"*.wav" = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""

# Images
"*.jpg" = ""
"*.jpeg" = ""
"*.png" = ""
"*.gif" = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp" = ""
"*.ico" = ""
"*.svg" = ""

# Programming
"*.c" = ""
"*.cpp" = ""
"*.h" = ""
"*.hpp" = ""
"*.rs" = ""
"*.go" = ""
"*.py" = ""
"*.js" = ""
"*.ts" = ""
"*.tsx" = ""
"*.jsx" = ""
"*.rb" = ""
"*.php" = ""
"*.java" = ""
"*.sh" = ""
"*.fish" = ""
"*.swift" = ""
"*.vim" = ""
"*.lua" = ""
"*.html" = ""
"*.css" = ""
"*.scss" = ""
"*.json" = ""
"*.toml" = ""
"*.yml" = ""
"*.yaml" = ""
"*.ini" = ""
"*.conf" = ""

# Default
"*" = ""
"*/" = ""

# : }}}
