[user]
name = "Azzam S.A"
email = "vcs@azzamsa.com"

[template-aliases]
'format_short_signature(signature)' = 'signature.name()' # default: 'signature.email()'

[aliases]
l = ["log", "-n", "5"]
ll = ["log", "-n", "5", "-r", "..@"]
