default_sort = "date" # default: name

# Default format for displaying files
default_format = "grid" # default: default (list)

# Whether to show icons by default
show_icons = true # default: false

# Whether to include directory sizes in file listings
include_dirs = false

# The theme to use for coloring
theme = "tokyo_night"

# List of enabled plugins
enabled_plugins = []

# Directory where plugins are stored
plugins_dir = "~/.config/lla/plugins"

# Maximum depth for recursive directory traversal
# Default: 3 levels deep
default_depth = 3

# Sorting configuration
[sort]
# List directories before files
dirs_first = false

# Enable case-sensitive sorting
case_sensitive = false

# Use natural sorting for numbers (e.g., 2.txt before 10.txt)
natural = true

# Filtering configuration
[filter]
# Enable case-sensitive filtering by default
case_sensitive = false

# Hide dot files and directories by default
no_dotfiles = true # default: false

# Formatter-specific configurations
[formatters.tree]
# Maximum number of entries to display in tree view
max_lines = 20000

# Lister-specific configurations
[listers.recursive]
# Maximum number of entries to process in recursive listing
max_entries = 20000

# Fuzzy lister configuration
[listers.fuzzy]
# Patterns to ignore when listing files in fuzzy mode
ignore_patterns = ["node_modules", "target", ".git", ".idea", ".vscode"]
