# Use mold as default linker
# https://github.com/rui314/mold#how-to-use
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

# https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html
[registries.crates-io]
protocol = "sparse"
