[gnome]
depends = ["global"]

#
# Shell
[shell.files]
# Will always be the default shell,
# otherwise cause unpopular app to breaks!
"shells/bash/bashrc" = "~/.bashrc"
"shells/bash/bash_profile" = "~/.bash_profile"

[shell.variables]
# defined in local variables
install = "echo not defined"
uninstall = "echo not defined"

[fish]
depends = ["shell"]

[fish.files]
"shells/fish" = "~/.config/fish"

[zsh]
depends = ["shell"]

[zsh.files]
"shells/zsh/zshenv" = "~/.zshenv"
"shells/zsh" = "~/.config/zsh"

[nushell]
depends = ["shell"]

[nushell.files]
"shells/nushell" = "~/.config/nushell"
"shells/nushell/themes" = { target = "~/.config/nushell/themes", type = "symbolic" }
"shells/nushell/extras" = { target = "~/.config/nushell/extras", type = "symbolic" }

#
# Terminals
[wezterm.files]
"terms/wezterm" = "~/.config/wezterm"

[kitty.files]
"terms/kitty" = "~/.config/kitty"

[alacritty.files]
"terms/alacritty" = "~/.config/alacritty"

#
# Fetchers
[fastfetch.files]
"fetchers/fastfetch" = "~/.config/fastfetch"

[macchina.files]
"fetchers/macchina" = "~/.config/macchina"

#
# Scripts
[bin.files]
"bin" = "~/.local/bin"

#
# Editor
[neovide.files]
"editors/neovide" = "~/.config/neovide"

[helix.files]
"editors/helix" = "~/.config/helix"

#
# VCS
[git.files]
"vcs/git" = "~/.config/git"

[jj.files]
"vcs/jj" = "~/.config/jj"

#
# Utils
[fontconfig.files]
"utils/fontconfig" = "~/.config/fontconfig"

[gnupg.files]
"utils/gnupg" = "~/.gnupg"

[starship.files]
"utils/starship/starship.toml" = "~/.config/starship.toml"

[atuin.files]
"utils/atuin" = "~/.config/atuin"

[zellij.files]
"utils/zellij" = "~/.config/zellij"

[yazi.files]
"utils/yazi" = "~/.config/yazi"
# Will be overridden by `post_deploy.sh`
"utils/yazi/theme.toml" = { target = "~/.config/yazi/theme.toml", type = "symbolic" }

[eget.files]
"utils/eget" = "~/.config/eget"

#
# Browsers
[tridactyl.files]
"browsers/tridactyl" = "~/.config/tridactyl"

#
# Programming Languages
[cargo.files]
"langs/cargo/config.toml" = "~/.cargo/config.toml"
