includes = [".dotter/include/fedora.toml"]

packages = [
    # Shell
    "bash",
    "fish",
    "nushell",

    # Terminals
    "wezterm",
    "kitty",
    "ghostty",
    "alacritty",
    # "rio",

    "foot",
    "starship",
    "atuin",
    "zellij",

    # Fetchers
    "fastfetch",

    # Editor
    "helix",
    "neovide",
    # "zed", two way edits

    # Scripts
    "bin",

    # VCS
    "git",
    "jj",

    # Utils
    "fontconfig",
    "gnupg",
    "yazi",
    # "lla",
    "eget",
    "jjui",
    # "sane-break" # sane-break doesn't work with symlink
    "mise",
    "satty",

    # Programming Languages
    "cargo",

    # Browsers
    # "tridactyl",

    # Window Managers
    "niri",
    "dms",
]

[variables]
user = "strider"
editor = "nvim"
terminal_font_size = 23
theme = "tokyo_black"
font = "0xProto Nerd Font"
terminal_font = "0xProto Nerd Font"
atuin_server = "https://shell.me.com"
