includes = [".dotter/include/fedora.toml"]

packages = [
    # Shell
    "shell",
    "fish",
    "nushell",

    # Terminals
    "wezterm",
    "kitty",
    "ghostty",
    "starship",
    "atuin",
    # "zellij",

    # Fetchers
    "fastfetch",

    # Editor
    "helix",
    "neovide",
    # "zed", two way edits

    # Scripts
    "bin",

    # VCS
    "git",
    "jj",

    # Utils
    "fontconfig",
    "gnupg",
    "yazi",
    # "lla",
    "eget",
    "jjui",
    # "sane-break" # sane-break doesn't work with symlink

    # Programming Languages
    "cargo",

    # Browsers
    # "tridactyl",
]

[variables]
editor = "nvim"
terminal_font_size = 21.5
theme = "modus_vivendi_tinted"
font = "Maple Mono NF"
atuin_server = "https://shell.me.com"
