name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Check code quality
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: taiki-e/install-action@1cf3de8de323df92fe08c793e53eaef58799aec4 # v2.68.3
        with:
          tool: just,dprint,typos,stylua,selene

      - name: Show version information
        shell: bash
        run: |
          dprint --version

      - name: Check
        run: |
          just check
