name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Check code quality
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:

      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: taiki-e/install-action@80e6af7a2ec7f280fffe2d0a9d3a12a9d11d86e9 # v2.75.1
        with:
          tool: just,dprint,typos,stylua,selene

      - name: Show version information
        shell: bash
        run: |
          dprint --version

      - name: Check
        run: |
          just check
