#!/usr/bin/env bash

# Load exports
if [ -f "$HOME/.exports" ]; then
	source "$HOME/.exports"
fi

eval "$(starship init bash)"
eval "$(fnm env --use-on-cd)"

. "$HOME/.config/meta/env"
. "$HOME/.local/share/cargo/env"
. "$HOME/.local/share/rye/env"
. "$HOME/.goup/env"
