#!/usr/bin/env bash

# Load exports
if [ -f "$HOME/.exports" ]; then
	source "$HOME/.exports"
fi

eval "$(atuin init bash)"
eval "$(starship init bash)"
eval "$(zoxide init bash)"
eval "$(mise activate bash)"

. "$HOME/.local/share/cargo/env"

#
# Private envs
if [ -f "$HOME/.config/meta/env" ]; then
    . "$HOME/.config/meta/env"
fi
